DROP USER IF EXISTS 'vicent'@'localhost';
DROP USER IF EXISTS 'vicent'@'127.0.0.1';
DROP USER IF EXISTS 'vicent'@'%';

CREATE USER 'vicent'@'127.0.0.1' IDENTIFIED BY 'passwdbd';
CREATE USER 'vicent'@'localhost' IDENTIFIED BY 'passwdbd';

CREATE DATABASE IF NOT EXISTS ARBOLADO;
GRANT ALL PRIVILEGES ON ARBOLADO.* TO 'vicent'@'127.0.0.1';
FLUSH PRIVILEGES;

USE ARBOLADO;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS arboles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    especie VARCHAR(50) NOT NULL,
    ubicacion VARCHAR(100) NOT NULL,
    fecha_plantacion DATE,
    estado ENUM('sano', 'enfermo', 'talado') DEFAULT 'sano',
    usuario_registro VARCHAR(50) NOT NULL
);
