DROP USER IF EXISTS 'vicent'@'localhost';
DROP USER IF EXISTS 'vicent'@'127.0.0.1';
DROP USER IF EXISTS 'vicent'@'%';

CREATE USER 'vicent'@'127.0.0.1' IDENTIFIED BY 'passwdbd';
CREATE USER 'vicent'@'localhost' IDENTIFIED BY 'passwdbd';

CREATE DATABASE IF NOT EXISTS ARBOLADO;
GRANT ALL PRIVILEGES ON ARBOLADO.* TO 'vicent'@'127.0.0.1';
FLUSH PRIVILEGES;
